# Generated by Django 5.0.2 on 2025-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("total_rating", models.FloatField(default=0)),
                ("category", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("coupon", models.CharField(blank=True, max_length=100, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                ("stock", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("benefits", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "package_dimension",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comments_reviews", models.TextField(blank=True, null=True)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
