# Generated by Django 5.0.2 on 2025-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_tag_remove_product_coupon_remove_product_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="package_dimension",
        ),
        migrations.AddField(
            model_name="product",
            name="breadth",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="benefits",
        ),
        migrations.AddField(
            model_name="product",
            name="benefits",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="dashboard.benefit"
            ),
        ),
    ]
