# Generated by Django 5.0.2 on 2025-05-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_comment_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="comments_reviews",
        ),
    ]
