# Generated by Django 5.0.2 on 2025-05-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_product_comments_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("amount", "Amount")],
                default="amount",
                max_length=10,
            ),
        ),
    ]
