# Generated by Django 5.0.2 on 2025-05-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_product_discount_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(max_length=255),
        ),
    ]
