# Generated by Django 5.0.8 on 2025-08-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_customerorder_orderitem_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='applied_coupon_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='applied_coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='applied_coupon_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percent'), ('amount', 'Amount')], max_length=10, null=True),
        ),
    ]
