# Generated by Django 5.0.2 on 2026-07-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
