# Generated by Django 5.0.2 on 2025-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slideshows/")),
                ("headline", models.CharField(max_length=200)),
                ("tagline", models.CharField(max_length=500)),
                ("link", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slideshow",
                "verbose_name_plural": "Slideshows",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
