# Generated by Django 5.0.2 on 2025-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slideshow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Slideshow",
                "verbose_name_plural": "Slideshows",
            },
        ),
        migrations.RemoveField(
            model_name="slideshow",
            name="order",
        ),
        migrations.AddField(
            model_name="slideshow",
            name="button_text",
            field=models.CharField(default="Learn More", max_length=200),
        ),
    ]
